[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -jar target/SpringBootSDPBackendProject-0.0.1-SNAPSHOT.jar"
numReplicas = 1
restartPolicyMaxRetries = 5
restartPolicyWindowSeconds = 60

[env]
PORT = "8080"
